name: ðŸ›¡ Secuity issue
description: Report a security issue or vulnerability.
title: 'security: '
labels: [security]

body:
  - type: markdown
    attributes:
      value: |
        # JioTV Go Security issue

        Important to note that your issue may have already been reported before. Please check for existing issues [here](https://github.com/rabilrbl/jiotv_go/labels/security).

  - type: textarea
    attributes:
      label: Security issue description
      description: How did you find the security issue? Any additional details that might help?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Add the steps to reproduce this security issue including your environment.
      placeholder: Step 1. Go to '...' Step 2. Click on '....' Step 3. Scroll down to '....'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks. Copy from terminal or log file and paste here.
      render: shell
    validations:
      required: false

  - type: textarea
    attributes:
      label: Screenshots or videos
      description: Add screenshots or videos that show the security issue here.
      placeholder: Drag and drop the screenshots/videos into this box.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Solution
      description: If applicable, add a possible solution.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add additional context here.
    validations:
      required: false

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you haven't done these steps.
      options:
        - label: I have searched the existing issues and this is a new and no duplicate or related to another open issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I filled out all of the requested information in this issue properly.
          required: true