name: Dependabot fetch metadata
on: pull_request

permissions:
  pull-requests: write
  issues: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    # Only run if the PR is from Dependabot
    if: github.actor == 'dependabot[bot]' 
    steps:
        - 
            name: Dependabot metadata
            id: dependabot-metadata
            uses: dependabot/fetch-metadata@v1
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
        -
            name: Checkout
            if: steps.dependabot-metadata.outputs.package-ecosystem == 'npm_and_yarn'
            uses: actions/checkout@v4
            with:
                ref: ${{ github.event.pull_request.head.ref }}
        -
            name: Setup Node.js
            if: steps.dependabot-metadata.outputs.package-ecosystem == 'npm_and_yarn'
            uses: actions/setup-node@v3
            with:
                node-version: latest
        -   
            name: Update tailwindcss with build changes
            if: steps.dependabot-metadata.outputs.package-ecosystem == 'npm_and_yarn'
            run: |
                npm ci && npm run build
                git add cmd/jiotv_go/static/tailwind.css
                git config user.name "github-actions[bot]"
                git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git commit -m "[dependabot skip] Update tailwindcss with build changes" || exit 0
                git push
